import { atom } from "recoil";

export const suggestionsState = atom({
  key: "suggestionsState",
  default: [
    "Gasolina",
    "Supermercado",
    "Restaurante",
    "Aluguel",
    "Conta de Luz",
    "Conta de Água",
    "Internet",
    "Telefone",
    "Transporte",
    "Lazer",
    "Saúde",
    "Educação",
    "Vestuário",
    "Presentes",
    "Investimentos",
    "Salário",
    "Freelance",
    "Reembolso",
    "Dividendos",
    "Transferência",
    "Doação",
    "Impostos",
    "Seguro",
    "Manutenção",
    "Pet",
    "Viagem",
    "Assinaturas",
    "Farmácia",
    "Beleza",
    "Outros",
  ],
});
